# Generated by Django 4.0.1 on 2022-01-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
    ]
