# Generated by Django 4.0.1 on 2022-01-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_menu_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='drink_allergen',
            old_name='allergen_id',
            new_name='allergen',
        ),
        migrations.RenameField(
            model_name='drink_allergen',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='size_id',
            new_name='size',
        ),
    ]
